import { ToastContainer } from "react-toastify";

import RootProvider from "./_providers/RootProvider";

import type { Metadata, Viewport } from "next";

import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="w-screen bg-zinc-50 overflow-x-hidden">
        <RootProvider>
          <main className="max-w-3xl bg-white mx-auto min-h-screen">
            {children}
          </main>
        </RootProvider>
        <ToastContainer
          position="top-center"
          autoClose={3000}
          hideProgressBar
          theme="colored"
        />
      </body>
    </html>
  );
}
