import type { Metadata } from "next";
import RootProvider from "@/shared/rootProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RootProvider>
      <html>
        <body className="flex h-screen w-screen items-center justify-center bg-zinc-50">
          <main className="flex h-screen w-full max-w-3xl flex-col items-center justify-between bg-white">
            {children}
          </main>
        </body>
      </html>
    </RootProvider>
  );
}
