export const COUNTRIES = [
  {
    name: "홋카이도",
    code: "JP-001",
    country: "JP",
    countryName: "일본",
  },
  { name: "아오모리현", code: "JP-002", country: "JP", countryName: "일본" },
  { name: "이와테현", code: "JP-003", country: "JP", countryName: "일본" },
  { name: "미야기현", code: "JP-004", country: "JP", countryName: "일본" },
  { name: "아키타현", code: "JP-005", country: "JP", countryName: "일본" },
  { name: "야마가타현", code: "JP-006", country: "JP", countryName: "일본" },
  { name: "후쿠시마현", code: "JP-007", country: "JP", countryName: "일본" },
  { name: "이바라키현", code: "JP-008", country: "JP", countryName: "일본" },
  { name: "토치기현", code: "JP-009", country: "JP", countryName: "일본" },
  { name: "군마현", code: "JP-010", country: "JP", countryName: "일본" },
  { name: "사이타마현", code: "JP-011", country: "JP", countryName: "일본" },
  { name: "지바현", code: "JP-012", country: "JP", countryName: "일본" },
  { name: "도쿄도", code: "JP-013", country: "JP", countryName: "일본" },
  { name: "가나가와현", code: "JP-014", country: "JP", countryName: "일본" },
  { name: "니가타현", code: "JP-015", country: "JP", countryName: "일본" },
  { name: "토야마현", code: "JP-016", country: "JP", countryName: "일본" },
  { name: "이시카와현", code: "JP-017", country: "JP", countryName: "일본" },
  { name: "후쿠이현", code: "JP-018", country: "JP", countryName: "일본" },
  { name: "야마나시현", code: "JP-019", country: "JP", countryName: "일본" },
  { name: "나가노현", code: "JP-020", country: "JP", countryName: "일본" },
  { name: "기후현", code: "JP-021", country: "JP", countryName: "일본" },
  { name: "시즈오카현", code: "JP-022", country: "JP", countryName: "일본" },
  { name: "아이치현", code: "JP-023", country: "JP", countryName: "일본" },
  { name: "미에현", code: "JP-024", country: "JP", countryName: "일본" },
  { name: "시가현", code: "JP-025", country: "JP", countryName: "일본" },
  { name: "교토부", code: "JP-026", country: "JP", countryName: "일본" },
  { name: "오사카부", code: "JP-027", country: "JP", countryName: "일본" },
  { name: "효고현", code: "JP-028", country: "JP", countryName: "일본" },
  { name: "나라현", code: "JP-029", country: "JP", countryName: "일본" },
  { name: "와카야마현", code: "JP-030", country: "JP", countryName: "일본" },
  { name: "돗토리현", code: "JP-031", country: "JP", countryName: "일본" },
  { name: "시마네현", code: "JP-032", country: "JP", countryName: "일본" },
  { name: "오카야마현", code: "JP-033", country: "JP", countryName: "일본" },
  { name: "히로시마현", code: "JP-034", country: "JP", countryName: "일본" },
  { name: "야마구치현", code: "JP-035", country: "JP", countryName: "일본" },
  { name: "도쿠시마현", code: "JP-036", country: "JP", countryName: "일본" },
  { name: "가가와현", code: "JP-037", country: "JP", countryName: "일본" },
  { name: "에히메현", code: "JP-038", country: "JP", countryName: "일본" },
  { name: "고치현", code: "JP-039", country: "JP", countryName: "일본" },
  { name: "후쿠오카현", code: "JP-040", country: "JP", countryName: "일본" },
  { name: "사가현", code: "JP-041", country: "JP", countryName: "일본" },
  { name: "나가사키현", code: "JP-042", country: "JP", countryName: "일본" },
  { name: "구마모토현", code: "JP-043", country: "JP", countryName: "일본" },
  { name: "오이타현", code: "JP-044", country: "JP", countryName: "일본" },
  { name: "미야자키현", code: "JP-045", country: "JP", countryName: "일본" },
  { name: "가고시마현", code: "JP-046", country: "JP", countryName: "일본" },
  { name: "오키나와현", code: "JP-047", country: "JP", countryName: "일본" },
  { name: "베이징시", code: "CN-001", country: "CN", countryName: "중국" },
  { name: "톈진시", code: "CN-002", country: "CN", countryName: "중국" },
  { name: "허베이성", code: "CN-003", country: "CN", countryName: "중국" },
  { name: "산시성(북부)", code: "CN-004", country: "CN", countryName: "중국" },
  { name: "내몽골자치구", code: "CN-005", country: "CN", countryName: "중국" },
  { name: "랴오닝성", code: "CN-006", country: "CN", countryName: "중국" },
  { name: "지린성", code: "CN-007", country: "CN", countryName: "중국" },
  { name: "헤이룽장성", code: "CN-008", country: "CN", countryName: "중국" },
  { name: "상하이시", code: "CN-009", country: "CN", countryName: "중국" },
  { name: "장쑤성", code: "CN-010", country: "CN", countryName: "중국" },
  { name: "저장성", code: "CN-011", country: "CN", countryName: "중국" },
  { name: "안후이성", code: "CN-012", country: "CN", countryName: "중국" },
  { name: "푸젠성", code: "CN-013", country: "CN", countryName: "중국" },
  { name: "장시성", code: "CN-014", country: "CN", countryName: "중국" },
  { name: "산둥성", code: "CN-015", country: "CN", countryName: "중국" },
  { name: "허난성", code: "CN-016", country: "CN", countryName: "중국" },
  { name: "후베이성", code: "CN-017", country: "CN", countryName: "중국" },
  { name: "후난성", code: "CN-018", country: "CN", countryName: "중국" },
  { name: "광둥성", code: "CN-019", country: "CN", countryName: "중국" },
  {
    name: "광시좡족자치구",
    code: "CN-020",
    country: "CN",
    countryName: "중국",
  },
  { name: "하이난성", code: "CN-021", country: "CN", countryName: "중국" },
  { name: "충칭시", code: "CN-022", country: "CN", countryName: "중국" },
  { name: "쓰촨성", code: "CN-023", country: "CN", countryName: "중국" },
  { name: "구이저우성", code: "CN-024", country: "CN", countryName: "중국" },
  { name: "윈난성", code: "CN-025", country: "CN", countryName: "중국" },
  { name: "시짱자치구", code: "CN-026", country: "CN", countryName: "중국" },
  { name: "산시성(서부)", code: "CN-027", country: "CN", countryName: "중국" },
  { name: "간쑤성", code: "CN-028", country: "CN", countryName: "중국" },
  { name: "칭하이성", code: "CN-029", country: "CN", countryName: "중국" },
  {
    name: "닝샤후이족자치구",
    code: "CN-030",
    country: "CN",
    countryName: "중국",
  },
  {
    name: "신장위구르자치구",
    code: "CN-031",
    country: "CN",
    countryName: "중국",
  },
  { name: "타이완", code: "CN-032", country: "CN", countryName: "중국" },
  {
    name: "홍콩특별행정구",
    code: "CN-033",
    country: "CN",
    countryName: "중국",
  },
  {
    name: "마카오특별행정구",
    code: "CN-034",
    country: "CN",
    countryName: "중국",
  },
  { name: "기타", code: "CN-035", country: "CN", countryName: "중국" },
  { name: "하노이", code: "HN", country: "VN", countryName: "베트남" },
  { name: "호찌민시", code: "SG", country: "VN", countryName: "베트남" },
  { name: "다낭", code: "DN", country: "VN", countryName: "베트남" },
  { name: "호이안 (꽝남)", code: "QN", country: "VN", countryName: "베트남" },
  {
    name: "후에 (투아티엔후에)",
    code: "TT",
    country: "VN",
    countryName: "베트남",
  },
  { name: "사파 (라오까이)", code: "LC", country: "VN", countryName: "베트남" },
  { name: "닌빈", code: "NB", country: "VN", countryName: "베트남" },
  {
    name: "팜반동 (하롱베이/꽝닌)",
    code: "QN2",
    country: "VN",
    countryName: "베트남",
  },
  {
    name: "무이네 (빈투언)",
    code: "BTH",
    country: "VN",
    countryName: "베트남",
  },
  { name: "달랏 (럼동)", code: "LD", country: "VN", countryName: "베트남" },
  { name: "냐짱 (카인화)", code: "KH", country: "VN", countryName: "베트남" },
  { name: "껀터", code: "CT", country: "VN", countryName: "베트남" },
  { name: "푸꾸옥 (끼엔장)", code: "KG", country: "VN", countryName: "베트남" },
  { name: "기타", code: "ETC", country: "VN", countryName: "베트남" },
  { name: "타이베이시", code: "TPE", country: "TW", countryName: "대만" },
  { name: "신베이시", code: "TPQ", country: "TW", countryName: "대만" },
  { name: "지룽시", code: "KEE", country: "TW", countryName: "대만" },
  { name: "타오위안시", code: "TAO", country: "TW", countryName: "대만" },
  { name: "타이중시", code: "TXG", country: "TW", countryName: "대만" },
  { name: "자이시", code: "CYI", country: "TW", countryName: "대만" },
  { name: "타이난시", code: "TNN", country: "TW", countryName: "대만" },
  { name: "가오슝시", code: "KHH", country: "TW", countryName: "대만" },
  { name: "화롄현", code: "HUA", country: "TW", countryName: "대만" },
  { name: "이란현", code: "ILA", country: "TW", countryName: "대만" },
  { name: "타이둥현", code: "TTT", country: "TW", countryName: "대만" },
  { name: "펑후현", code: "PEN", country: "TW", countryName: "대만" },
  { name: "기타", code: "ETC", country: "TW", countryName: "대만" },
  { name: "마닐라 수도권", code: "NCR", country: "PH", countryName: "필리핀" },
  { name: "세부", code: "CEB", country: "PH", countryName: "필리핀" },
  { name: "다바오", code: "DAV", country: "PH", countryName: "필리핀" },
  { name: "일로일로", code: "ILI", country: "PH", countryName: "필리핀" },
  { name: "기타", code: "ETC", country: "PH", countryName: "필리핀" },
  { name: "자카르타", code: "JK", country: "ID", countryName: "인도네시아" },
  { name: "서자바주", code: "JB", country: "ID", countryName: "인도네시아" },
  { name: "중자바주", code: "JT", country: "ID", countryName: "인도네시아" },
  { name: "동자바주", code: "JI", country: "ID", countryName: "인도네시아" },
  { name: "발리", code: "BA", country: "ID", countryName: "인도네시아" },
  {
    name: "북수마트라주",
    code: "SU",
    country: "ID",
    countryName: "인도네시아",
  },
  {
    name: "남술라웨시주",
    code: "SN",
    country: "ID",
    countryName: "인도네시아",
  },
  { name: "기타", code: "ETC", country: "ID", countryName: "인도네시아" },
  {
    name: "센트럴 지역",
    code: "CENTRAL",
    country: "SG",
    countryName: "싱가포르",
  },
  { name: "동부 지역", code: "EAST", country: "SG", countryName: "싱가포르" },
  { name: "서부 지역", code: "WEST", country: "SG", countryName: "싱가포르" },
  { name: "북부 지역", code: "NORTH", country: "SG", countryName: "싱가포르" },
  {
    name: "북동부 지역",
    code: "NORTHEAST",
    country: "SG",
    countryName: "싱가포르",
  },
  { name: "방콕", code: "BKK", country: "TH", countryName: "태국" },
  { name: "치앙마이", code: "CNX", country: "TH", countryName: "태국" },
  { name: "푸껫", code: "HKT", country: "TH", countryName: "태국" },
  { name: "콘깬", code: "KKC", country: "TH", countryName: "태국" },
  { name: "우돈타니", code: "UTH", country: "TH", countryName: "태국" },
  { name: "핫야이 (송클라)", code: "HDY", country: "TH", countryName: "태국" },
  { name: "기타", code: "ETC", country: "TH", countryName: "태국" },
  { name: "프놈펜", code: "PNH", country: "KH", countryName: "캄보디아" },
  { name: "씨엠립", code: "REP", country: "KH", countryName: "캄보디아" },
  { name: "시하누크빌", code: "KOS", country: "KH", countryName: "캄보디아" },
  { name: "기타", code: "ETC", country: "KH", countryName: "캄보디아" },
  { name: "비엔티안", code: "VTE", country: "LA", countryName: "라오스" },
  { name: "루앙프라방", code: "LPQ", country: "LA", countryName: "라오스" },
  { name: "팍세", code: "PKZ", country: "LA", countryName: "라오스" },
  { name: "기타", code: "ETC", country: "LA", countryName: "라오스" },
  { name: "양곤", code: "RGN", country: "MM", countryName: "미얀마" },
  { name: "만달레이", code: "MDL", country: "MM", countryName: "미얀마" },
  { name: "네피도", code: "NYT", country: "MM", countryName: "미얀마" },
  { name: "기타", code: "ETC", country: "MM", countryName: "미얀마" },
  { name: "델리", code: "DL", country: "IN", countryName: "인도" },
  {
    name: "마하라슈트라주 (뭄바이)",
    code: "MH",
    country: "IN",
    countryName: "인도",
  },
  {
    name: "타밀나두주 (첸나이)",
    code: "TN",
    country: "IN",
    countryName: "인도",
  },
  {
    name: "카르나타카주 (벵갈루루)",
    code: "KA",
    country: "IN",
    countryName: "인도",
  },
  {
    name: "우타르프라데시주 (아그라 등)",
    code: "UP",
    country: "IN",
    countryName: "인도",
  },
  {
    name: "라자스탄주 (자이푸르 등)",
    code: "RJ",
    country: "IN",
    countryName: "인도",
  },
  { name: "고아", code: "GA", country: "IN", countryName: "인도" },
  { name: "기타", code: "ETC", country: "IN", countryName: "인도" },
  { name: "울란바토르", code: "UB", country: "MN", countryName: "몽골" },
  {
    name: "고비사막 지역 (둔드고비, 남고비)",
    code: "GOV",
    country: "MN",
    countryName: "몽골",
  },
  { name: "홉스골 아이막", code: "KHU", country: "MN", countryName: "몽골" },
  {
    name: "아르항가이 아이막",
    code: "ARK",
    country: "MN",
    countryName: "몽골",
  },
  { name: "기타", code: "ETC", country: "MN", countryName: "몽골" },
  { name: "모스크바", code: "MOW", country: "RU", countryName: "러시아" },
  {
    name: "상트페테르부르크",
    code: "SPE",
    country: "RU",
    countryName: "러시아",
  },
  {
    name: "이르쿠츠크 (바이칼호)",
    code: "IRK",
    country: "RU",
    countryName: "러시아",
  },
  { name: "블라디보스토크", code: "VVO", country: "RU", countryName: "러시아" },
  { name: "노보시비르스크", code: "NVS", country: "RU", countryName: "러시아" },
  { name: "기타", code: "ETC", country: "RU", countryName: "러시아" },
  { name: "알마티", code: "ALA", country: "KZ", countryName: "카자흐스탄" },
  {
    name: "아스타나 (누르술탄)",
    code: "AST",
    country: "KZ",
    countryName: "카자흐스탄",
  },
  { name: "치믐켄트", code: "SHY", country: "KZ", countryName: "카자흐스탄" },
  { name: "기타", code: "ETC", country: "KZ", countryName: "카자흐스탄" },
  { name: "비슈케크", code: "BIS", country: "KG", countryName: "키르기스스탄" },
  {
    name: "이식쿨 주 (카라콜 포함)",
    code: "IK",
    country: "KG",
    countryName: "키르기스스탄",
  },
  { name: "오시 주", code: "OSH", country: "KG", countryName: "키르기스스탄" },
  { name: "기타", code: "ETC", country: "KG", countryName: "키르기스스탄" },
  { name: "다카 구", code: "DHK", country: "BD", countryName: "방글라데시" },
  { name: "치타공 구", code: "CTG", country: "BD", countryName: "방글라데시" },
  { name: "쿨나 구", code: "KHL", country: "BD", countryName: "방글라데시" },
  {
    name: "라지샤히 구",
    code: "RAJ",
    country: "BD",
    countryName: "방글라데시",
  },
  { name: "실헷 구", code: "SYL", country: "BD", countryName: "방글라데시" },
  { name: "기타", code: "ETC", country: "BD", countryName: "방글라데시" },
  { name: "티엠푸", code: "THI", country: "BT", countryName: "부탄" },
  { name: "파로", code: "PAR", country: "BT", countryName: "부탄" },
  { name: "펀초링 (추카 현)", code: "PHU", country: "BT", countryName: "부탄" },
  { name: "붐탕 현", code: "BUM", country: "BT", countryName: "부탄" },
  { name: "강떡 현", code: "GNT", country: "BT", countryName: "부탄" },
  { name: "기타", code: "ETC", country: "BT", countryName: "부탄" },
  {
    name: "바그마티 주 (카트만두 포함)",
    code: "BAG",
    country: "NP",
    countryName: "네팔",
  },
  {
    name: "간다키 주 (포카라 포함)",
    code: "GAN",
    country: "NP",
    countryName: "네팔",
  },
  {
    name: "루믹 지역 (룸비니 포함)",
    code: "LUM",
    country: "NP",
    countryName: "네팔",
  },
  { name: "수드루파슈침 주", code: "SUD", country: "NP", countryName: "네팔" },
  { name: "기타", code: "ETC", country: "NP", countryName: "네팔" },
  { name: "두샨베", code: "DUS", country: "TJ", countryName: "타지키스탄" },
  {
    name: "호로그 (고르노-바다흐샨 자치주)",
    code: "GBL",
    country: "TJ",
    countryName: "타지키스탄",
  },
  {
    name: "수그드 주 (호잔드 포함)",
    code: "SGD",
    country: "TJ",
    countryName: "타지키스탄",
  },
  {
    name: "기쥴로바트 주",
    code: "KHT",
    country: "TJ",
    countryName: "타지키스탄",
  },
  { name: "기타", code: "ETC", country: "TJ", countryName: "타지키스탄" },
  {
    name: "이슬라마바드 수도권",
    code: "ISB",
    country: "PK",
    countryName: "파키스탄",
  },
  {
    name: "펀자브 주 (라호르 포함)",
    code: "PJB",
    country: "PK",
    countryName: "파키스탄",
  },
  {
    name: "신드 주 (카라치 포함)",
    code: "SD",
    country: "PK",
    countryName: "파키스탄",
  },
  {
    name: "길기트-발티스탄",
    code: "GB",
    country: "PK",
    countryName: "파키스탄",
  },
  {
    name: "카이버르파크툰크와 주 (페샤와르 포함)",
    code: "KP",
    country: "PK",
    countryName: "파키스탄",
  },
  { name: "기타", code: "ETC", country: "PK", countryName: "파키스탄" },
  { name: "카불 주", code: "KBL", country: "AF", countryName: "아프가니스탄" },
  {
    name: "헤라트 주",
    code: "HER",
    country: "AF",
    countryName: "아프가니스탄",
  },
  {
    name: "발흐 주 (마자르이샤리프)",
    code: "BAL",
    country: "AF",
    countryName: "아프가니스탄",
  },
  { name: "밤얀 주", code: "BAM", country: "AF", countryName: "아프가니스탄" },
  { name: "기타", code: "ETC", country: "AF", countryName: "아프가니스탄" },
  {
    name: "아스타나 (누르술탄)",
    code: "AST",
    country: "KZ",
    countryName: "카자흐스탄",
  },
  { name: "알마티", code: "ALA", country: "KZ", countryName: "카자흐스탄" },
  {
    name: "카라간다 주",
    code: "KAR",
    country: "KZ",
    countryName: "카자흐스탄",
  },
  {
    name: "악타우 (망기스타우 주)",
    code: "AKT",
    country: "KZ",
    countryName: "카자흐스탄",
  },
  { name: "기타", code: "ETC", country: "KZ", countryName: "카자흐스탄" },
  { name: "타슈켄트", code: "TAS", country: "UZ", countryName: "우즈베키스탄" },
  {
    name: "사마르칸트 주",
    code: "SAM",
    country: "UZ",
    countryName: "우즈베키스탄",
  },
  {
    name: "부하라 주",
    code: "BUK",
    country: "UZ",
    countryName: "우즈베키스탄",
  },
  {
    name: "히바 (호라즘 주)",
    code: "KHW",
    country: "UZ",
    countryName: "우즈베키스탄",
  },
  { name: "기타", code: "ETC", country: "UZ", countryName: "우즈베키스탄" },
  {
    name: "아슈하바트",
    code: "ASH",
    country: "TM",
    countryName: "투르크메니스탄",
  },
  {
    name: "마리 주",
    code: "MAR",
    country: "TM",
    countryName: "투르크메니스탄",
  },
  {
    name: "다쇼구즈 주",
    code: "DAS",
    country: "TM",
    countryName: "투르크메니스탄",
  },
  {
    name: "바르칸 주",
    code: "BKN",
    country: "TM",
    countryName: "투르크메니스탄",
  },
  { name: "기타", code: "ETC", country: "TM", countryName: "투르크메니스탄" },
  { name: "테헤란 주", code: "TEH", country: "IR", countryName: "이란" },
  { name: "이스파한 주", code: "ISF", country: "IR", countryName: "이란" },
  {
    name: "시라즈 (파르스 주)",
    code: "FRS",
    country: "IR",
    countryName: "이란",
  },
  { name: "야즈드 주", code: "YZD", country: "IR", countryName: "이란" },
  {
    name: "마슈하드 (호라산 주)",
    code: "KHN",
    country: "IR",
    countryName: "이란",
  },
  { name: "기타", code: "ETC", country: "IR", countryName: "이란" },
  { name: "바그다드 주", code: "BGD", country: "IQ", countryName: "이라크" },
  {
    name: "아르빌 (쿠르드 자치구)",
    code: "ARB",
    country: "IQ",
    countryName: "이라크",
  },
  { name: "나자프 주", code: "NAJ", country: "IQ", countryName: "이라크" },
  { name: "바스라 주", code: "BSR", country: "IQ", countryName: "이라크" },
  { name: "기타", code: "ETC", country: "IQ", countryName: "이라크" },
  { name: "다마스쿠스", code: "DAM", country: "SY", countryName: "시리아" },
  { name: "알레포 주", code: "ALE", country: "SY", countryName: "시리아" },
  { name: "홈스 주", code: "HOM", country: "SY", countryName: "시리아" },
  { name: "라타키아 주", code: "LAT", country: "SY", countryName: "시리아" },
  { name: "기타", code: "ETC", country: "SY", countryName: "시리아" },
  { name: "베이루트", code: "BEY", country: "LB", countryName: "레바논" },
  {
    name: "북부 주 (트리폴리 포함)",
    code: "NTH",
    country: "LB",
    countryName: "레바논",
  },
  {
    name: "남부 주 (시돈 포함)",
    code: "STH",
    country: "LB",
    countryName: "레바논",
  },
  {
    name: "베카 주 (바알벡 포함)",
    code: "BEK",
    country: "LB",
    countryName: "레바논",
  },
  { name: "기타", code: "ETC", country: "LB", countryName: "레바논" },
  { name: "예루살렘", code: "JRS", country: "IL", countryName: "이스라엘" },
  { name: "텔아비브 주", code: "TLV", country: "IL", countryName: "이스라엘" },
  { name: "하이파 주", code: "HFA", country: "IL", countryName: "이스라엘" },
  {
    name: "남부 주 (네게브 포함)",
    code: "SOU",
    country: "IL",
    countryName: "이스라엘",
  },
  { name: "기타", code: "ETC", country: "IL", countryName: "이스라엘" },
  { name: "암만", code: "AMM", country: "JO", countryName: "요르단" },
  {
    name: "페트라 (마안 주)",
    code: "MAA",
    country: "JO",
    countryName: "요르단",
  },
  { name: "아카바 주", code: "AQB", country: "JO", countryName: "요르단" },
  { name: "자르카 주", code: "ZAR", country: "JO", countryName: "요르단" },
  { name: "기타", code: "ETC", country: "JO", countryName: "요르단" },
  {
    name: "리야드 주",
    code: "RYD",
    country: "SA",
    countryName: "사우디아라비아",
  },
  {
    name: "메카 주 (메카, 제다 포함)",
    code: "MEK",
    country: "SA",
    countryName: "사우디아라비아",
  },
  {
    name: "메디나 주",
    code: "MED",
    country: "SA",
    countryName: "사우디아라비아",
  },
  {
    name: "담맘 (동부 주)",
    code: "DMM",
    country: "SA",
    countryName: "사우디아라비아",
  },
  { name: "기타", code: "ETC", country: "SA", countryName: "사우디아라비아" },
  { name: "두바이", code: "DXB", country: "AE", countryName: "아랍에미리트" },
  { name: "아부다비", code: "AUH", country: "AE", countryName: "아랍에미리트" },
  { name: "샤르자", code: "SHJ", country: "AE", countryName: "아랍에미리트" },
  {
    name: "라스알카이마",
    code: "RAK",
    country: "AE",
    countryName: "아랍에미리트",
  },
  { name: "기타", code: "ETC", country: "AE", countryName: "아랍에미리트" },
  { name: "무스카트 주", code: "MCT", country: "OM", countryName: "오만" },
  {
    name: "다르지야 주 (니즈와 포함)",
    code: "DAH",
    country: "OM",
    countryName: "오만",
  },
  {
    name: "살랄라 (도파르 주)",
    code: "SLL",
    country: "OM",
    countryName: "오만",
  },
  { name: "기타", code: "ETC", country: "OM", countryName: "오만" },
  { name: "사나", code: "SAH", country: "YE", countryName: "예멘" },
  { name: "아덴", code: "ADE", country: "YE", countryName: "예멘" },
  {
    name: "하드라마우트 주 (무칼라 포함)",
    code: "HAD",
    country: "YE",
    countryName: "예멘",
  },
  { name: "기타", code: "ETC", country: "YE", countryName: "예멘" },
  {
    name: "뉴사우스웨일스 주 (시드니)",
    code: "NSW",
    country: "AU",
    countryName: "호주",
  },
  {
    name: "빅토리아 주 (멜버른)",
    code: "VIC",
    country: "AU",
    countryName: "호주",
  },
  {
    name: "퀸즐랜드 주 (브리즈번)",
    code: "QLD",
    country: "AU",
    countryName: "호주",
  },
  {
    name: "웨스턴오스트레일리아 주 (퍼스)",
    code: "WA",
    country: "AU",
    countryName: "호주",
  },
  {
    name: "사우스오스트레일리아 주 (애들레이드)",
    code: "SA",
    country: "AU",
    countryName: "호주",
  },
  {
    name: "태즈메이니아 주 (호바트)",
    code: "TAS",
    country: "AU",
    countryName: "호주",
  },
  {
    name: "노던 테리토리 (다윈)",
    code: "NT",
    country: "AU",
    countryName: "호주",
  },
  {
    name: "캔버라 (ACT 특별구)",
    code: "ACT",
    country: "AU",
    countryName: "호주",
  },
  { name: "기타", code: "ETC", country: "AU", countryName: "호주" },
  {
    name: "쿠알라룸푸르",
    code: "KUL",
    country: "MY",
    countryName: "말레이시아",
  },
  {
    name: "세랑고르 주 (푸트라자야 포함)",
    code: "SGR",
    country: "MY",
    countryName: "말레이시아",
  },
  {
    name: "페낭 주 (조지타운)",
    code: "PNG",
    country: "MY",
    countryName: "말레이시아",
  },
  { name: "말라카 주", code: "MLK", country: "MY", countryName: "말레이시아" },
  {
    name: "조호르 주 (조호르바루)",
    code: "JHR",
    country: "MY",
    countryName: "말레이시아",
  },
  {
    name: "사바 주 (코타키나발루)",
    code: "SBH",
    country: "MY",
    countryName: "말레이시아",
  },
  {
    name: "사라왁 주 (쿠칭)",
    code: "SWK",
    country: "MY",
    countryName: "말레이시아",
  },
  { name: "기타", code: "ETC", country: "MY", countryName: "말레이시아" },
  {
    name: "카사블랑카-세타트",
    code: "CAS",
    country: "MA",
    countryName: "모로코",
  },
  { name: "마라케시-사피", code: "MRK", country: "MA", countryName: "모로코" },
  { name: "페즈-메크네스", code: "FEZ", country: "MA", countryName: "모로코" },
  {
    name: "라바트-살레-케니트라",
    code: "RAB",
    country: "MA",
    countryName: "모로코",
  },
  {
    name: "탕헤르-테투안-알호세이마",
    code: "TNG",
    country: "MA",
    countryName: "모로코",
  },
  { name: "기타", code: "ETC", country: "MA", countryName: "모로코" },
  {
    name: "튀니스 주 (수도권)",
    code: "TUN",
    country: "TN",
    countryName: "튀니지",
  },
  { name: "수스 주", code: "SUS", country: "TN", countryName: "튀니지" },
  { name: "모나스티르 주", code: "MON", country: "TN", countryName: "튀니지" },
  { name: "마디아 주", code: "MAH", country: "TN", countryName: "튀니지" },
  {
    name: "도우즈 (케빌리 주)",
    code: "DOU",
    country: "TN",
    countryName: "튀니지",
  },
  { name: "기타", code: "ETC", country: "TN", countryName: "튀니지" },
  { name: "알제 주 (알제)", code: "ALG", country: "DZ", countryName: "알제리" },
  { name: "오란 주", code: "ORN", country: "DZ", countryName: "알제리" },
  { name: "콘스탄틴 주", code: "CON", country: "DZ", countryName: "알제리" },
  { name: "가르다이아 주", code: "GHA", country: "DZ", countryName: "알제리" },
  { name: "기타", code: "ETC", country: "DZ", countryName: "알제리" },
  { name: "엘아윤", code: "EUN", country: "EH", countryName: "서사하라" },
  { name: "다클라", code: "DAK", country: "EH", countryName: "서사하라" },
  { name: "기타", code: "ETC", country: "EH", countryName: "서사하라" },
  {
    name: "누악쇼트 주 (수도권)",
    code: "NKC",
    country: "MR",
    countryName: "모리타니",
  },
  {
    name: "아타르 (아드라르 주)",
    code: "ATR",
    country: "MR",
    countryName: "모리타니",
  },
  { name: "기타", code: "ETC", country: "MR", countryName: "모리타니" },
  { name: "트리폴리 주", code: "TIP", country: "LY", countryName: "리비아" },
  { name: "벵가지 주", code: "BEN", country: "LY", countryName: "리비아" },
  { name: "사브하 주", code: "SEB", country: "LY", countryName: "리비아" },
  { name: "기타", code: "ETC", country: "LY", countryName: "리비아" },
  { name: "카이로 주", code: "CAI", country: "EG", countryName: "이집트" },
  {
    name: "알렉산드리아 주",
    code: "ALX",
    country: "EG",
    countryName: "이집트",
  },
  { name: "기자 주", code: "GIZ", country: "EG", countryName: "이집트" },
  { name: "룩소르 주", code: "LXR", country: "EG", countryName: "이집트" },
  { name: "아스완 주", code: "ASW", country: "EG", countryName: "이집트" },
  {
    name: "홍해 주 (후르가다)",
    code: "RDH",
    country: "EG",
    countryName: "이집트",
  },
  {
    name: "시나이 주 (샤름엘셰이크)",
    code: "SIN",
    country: "EG",
    countryName: "이집트",
  },
  { name: "기타", code: "ETC", country: "EG", countryName: "이집트" },
  { name: "누악쇼트 주", code: "NKC", country: "MR", countryName: "모리타니" },
  {
    name: "아타르 (아드라르 주)",
    code: "ADR",
    country: "MR",
    countryName: "모리타니",
  },
  { name: "기타", code: "ETC", country: "MR", countryName: "모리타니" },
  { name: "바마코", code: "BKO", country: "ML", countryName: "말리" },
  { name: "모프티 주", code: "MOP", country: "ML", countryName: "말리" },
  { name: "팀북투 주", code: "TOM", country: "ML", countryName: "말리" },
  { name: "기타", code: "ETC", country: "ML", countryName: "말리" },
  { name: "니아메 주", code: "NIM", country: "NE", countryName: "니제르" },
  { name: "아가데즈 주", code: "AGD", country: "NE", countryName: "니제르" },
  { name: "마라디 주", code: "MAR", country: "NE", countryName: "니제르" },
  { name: "기타", code: "ETC", country: "NE", countryName: "니제르" },
  { name: "은자메나 주", code: "NDJ", country: "TD", countryName: "차드" },
  { name: "마오 주", code: "MAO", country: "TD", countryName: "차드" },
  { name: "아베셰 주", code: "ABE", country: "TD", countryName: "차드" },
  { name: "기타", code: "ETC", country: "TD", countryName: "차드" },
  { name: "하르툼 주", code: "KRT", country: "SD", countryName: "수단" },
  {
    name: "카르다판 주 (엘오베이드)",
    code: "KRT-KD",
    country: "SD",
    countryName: "수단",
  },
  {
    name: "다르푸르 주 (엘파셰르)",
    code: "KRT-DF",
    country: "SD",
    countryName: "수단",
  },
  { name: "기타", code: "ETC", country: "SD", countryName: "수단" },
  {
    name: "아스마라 (중앙 주)",
    code: "ASM",
    country: "ER",
    countryName: "에리트레아",
  },
  {
    name: "마사와 (남홍해 주)",
    code: "MSW",
    country: "ER",
    countryName: "에리트레아",
  },
  { name: "기타", code: "ETC", country: "ER", countryName: "에리트레아" },
  { name: "다카르", code: "DKR", country: "SN", countryName: "세네갈" },
  { name: "생루이", code: "SL", country: "SN", countryName: "세네갈" },
  {
    name: "카사망스 (지긴쇼르 포함)",
    code: "CSM",
    country: "SN",
    countryName: "세네갈",
  },
  { name: "기타", code: "ETC", country: "SN", countryName: "세네갈" },
  { name: "기니", code: "GN", country: "GN", countryName: "기니" },
  {
    name: "부르키나파소",
    code: "BF",
    country: "BF",
    countryName: "부르키나파소",
  },
  { name: "코토누", code: "CO", country: "BJ", countryName: "베냉" },
  { name: "포르토노보", code: "PN", country: "BJ", countryName: "베냉" },
  { name: "아보메이", code: "AB", country: "BJ", countryName: "베냉" },
  { name: "기타", code: "ETC", country: "BJ", countryName: "베냉" },
  { name: "로메", code: "LFW", country: "TG", countryName: "토고" },
  { name: "기타", code: "ETC", country: "TG", countryName: "토고" },
  { name: "아크라", code: "ACC", country: "GH", countryName: "가나" },
  { name: "케이프코스트", code: "CC", country: "GH", countryName: "가나" },
  { name: "쿠마시", code: "KSI", country: "GH", countryName: "가나" },
  { name: "기타", code: "ETC", country: "GH", countryName: "가나" },
  { name: "아비장", code: "ABJ", country: "CI", countryName: "코트디부아르" },
  {
    name: "야무수크로",
    code: "YAM",
    country: "CI",
    countryName: "코트디부아르",
  },
  { name: "기타", code: "ETC", country: "CI", countryName: "코트디부아르" },
  { name: "프리타운", code: "FNA", country: "SL", countryName: "시에라리온" },
  { name: "기타", code: "ETC", country: "SL", countryName: "시에라리온" },
  { name: "라이베리아", code: "LR", country: "LR", countryName: "라이베리아" },
  { name: "반줄", code: "BJL", country: "GM", countryName: "감비아" },
  { name: "세레쿤다", code: "SER", country: "GM", countryName: "감비아" },
  { name: "기타", code: "ETC", country: "GM", countryName: "감비아" },
  {
    name: "아부자 수도권",
    code: "FC",
    country: "NG",
    countryName: "나이지리아",
  },
  { name: "라고스 주", code: "LA", country: "NG", countryName: "나이지리아" },
  { name: "카노 주", code: "KN", country: "NG", countryName: "나이지리아" },
  {
    name: "이바단 (오요 주)",
    code: "OY",
    country: "NG",
    countryName: "나이지리아",
  },
  {
    name: "포트하커트 (리버스 주)",
    code: "RI",
    country: "NG",
    countryName: "나이지리아",
  },
  { name: "기타", code: "ETC", country: "NG", countryName: "나이지리아" },
  { name: "야운데", code: "CE", country: "CM", countryName: "카메룬" },
  { name: "두알라", code: "LT", country: "CM", countryName: "카메룬" },
  { name: "기타", code: "ETC", country: "CM", countryName: "카메룬" },
  {
    name: "중앙아프리카공화국",
    code: "CF",
    country: "CF",
    countryName: "중앙아프리카공화국",
  },
  { name: "주바", code: "JUB", country: "SS", countryName: "남수단" },
  { name: "기타", code: "ETC", country: "SS", countryName: "남수단" },
  {
    name: "아디스아바바",
    code: "AA",
    country: "ET",
    countryName: "에티오피아",
  },
  {
    name: "라리벨라 (암하라 주)",
    code: "AM",
    country: "ET",
    countryName: "에티오피아",
  },
  {
    name: "곤다르 (암하라 주)",
    code: "GD",
    country: "ET",
    countryName: "에티오피아",
  },
  { name: "기타", code: "ETC", country: "ET", countryName: "에티오피아" },
  { name: "지부티 시", code: "DJ", country: "DJ", countryName: "지부티" },
  { name: "기타", code: "ETC", country: "DJ", countryName: "지부티" },
  { name: "말라보", code: "ML", country: "GQ", countryName: "적도기니" },
  { name: "바타", code: "BT", country: "GQ", countryName: "적도기니" },
  { name: "기타", code: "ETC", country: "GQ", countryName: "적도기니" },
  { name: "리브르빌", code: "LBV", country: "GA", countryName: "가봉" },
  { name: "프랑스빌", code: "FR", country: "GA", countryName: "가봉" },
  { name: "기타", code: "ETC", country: "GA", countryName: "가봉" },
  { name: "브라자빌", code: "BZV", country: "CG", countryName: "콩고공화국" },
  {
    name: "푸앵트누아르",
    code: "PNR",
    country: "CG",
    countryName: "콩고공화국",
  },
  { name: "기타", code: "ETC", country: "CG", countryName: "콩고공화국" },
  { name: "킨샤사", code: "KIN", country: "CD", countryName: "콩고민주공화국" },
  {
    name: "루붐바시",
    code: "LUB",
    country: "CD",
    countryName: "콩고민주공화국",
  },
  { name: "기타", code: "ETC", country: "CD", countryName: "콩고민주공화국" },
  { name: "캄팔라", code: "KLA", country: "UG", countryName: "우간다" },
  { name: "엔테베", code: "EBB", country: "UG", countryName: "우간다" },
  { name: "기타", code: "ETC", country: "UG", countryName: "우간다" },
  { name: "나이로비", code: "NBO", country: "KE", countryName: "케냐" },
  { name: "몸바사", code: "MBA", country: "KE", countryName: "케냐" },
  { name: "기타", code: "ETC", country: "KE", countryName: "케냐" },
  { name: "모가디슈", code: "MGQ", country: "SO", countryName: "소말리아" },
  { name: "기타", code: "ETC", country: "SO", countryName: "소말리아" },
  { name: "키갈리", code: "KGL", country: "RW", countryName: "르완다" },
  { name: "기타", code: "ETC", country: "RW", countryName: "르완다" },
  { name: "기테가", code: "KRT", country: "BI", countryName: "부룬디" },
  { name: "기타", code: "ETC", country: "BI", countryName: "부룬디" },
  { name: "다르에스살람", code: "DAR", country: "TZ", countryName: "탄자니아" },
  { name: "잔지바르", code: "ZNZ", country: "TZ", countryName: "탄자니아" },
  { name: "기타", code: "ETC", country: "TZ", countryName: "탄자니아" },
  { name: "루안다", code: "LAD", country: "AO", countryName: "앙골라" },
  {
    name: "우앙줄루 (벤겔라주)",
    code: "UGZ",
    country: "AO",
    countryName: "앙골라",
  },
  { name: "기타", code: "ETC", country: "AO", countryName: "앙골라" },
  { name: "루사카", code: "LUN", country: "ZM", countryName: "잠비아" },
  { name: "기타", code: "ETC", country: "ZM", countryName: "잠비아" },
  { name: "릴롱궤", code: "LLW", country: "MW", countryName: "말라위" },
  { name: "블랜타이어", code: "BLZ", country: "MW", countryName: "말라위" },
  { name: "기타", code: "ETC", country: "MW", countryName: "말라위" },
  { name: "하라레", code: "HRE", country: "ZW", countryName: "짐바브웨" },
  { name: "불라와요", code: "BUQ", country: "ZW", countryName: "짐바브웨" },
  { name: "기타", code: "ETC", country: "ZW", countryName: "짐바브웨" },
  { name: "마푸토", code: "MPM", country: "MZ", countryName: "모잠비크" },
  {
    name: "빌라루무 (자보라 주)",
    code: "ZBB",
    country: "MZ",
    countryName: "모잠비크",
  },
  { name: "기타", code: "ETC", country: "MZ", countryName: "모잠비크" },
  { name: "빈트후크", code: "KH", country: "NA", countryName: "나미비아" },
  { name: "스와코프문트", code: "ER", country: "NA", countryName: "나미비아" },
  { name: "월비스베이", code: "ER-WB", country: "NA", countryName: "나미비아" },
  { name: "기타", code: "ETC", country: "NA", countryName: "나미비아" },
  { name: "가보로네", code: "GA", country: "BW", countryName: "보츠와나" },
  { name: "마운", code: "NG", country: "BW", countryName: "보츠와나" },
  { name: "카사네", code: "CH", country: "BW", countryName: "보츠와나" },
  { name: "기타", code: "ETC", country: "BW", countryName: "보츠와나" },
  { name: "음바바네", code: "H", country: "SZ", countryName: "에스와티니" },
  { name: "로밤바", code: "M", country: "SZ", countryName: "에스와티니" },
  { name: "기타", code: "ETC", country: "SZ", countryName: "에스와티니" },
  { name: "마세루", code: "MS", country: "LS", countryName: "레소토" },
  { name: "기타", code: "ETC", country: "LS", countryName: "레소토" },
  {
    name: "요하네스버그",
    code: "GT-JHB",
    country: "ZA",
    countryName: "남아프리카공화국",
  },
  {
    name: "케이프타운",
    code: "WC-CT",
    country: "ZA",
    countryName: "남아프리카공화국",
  },
  {
    name: "더반",
    code: "KZN-DBN",
    country: "ZA",
    countryName: "남아프리카공화국",
  },
  {
    name: "프리토리아",
    code: "GT-PTA",
    country: "ZA",
    countryName: "남아프리카공화국",
  },
  {
    name: "포트엘리자베스",
    code: "EC-PE",
    country: "ZA",
    countryName: "남아프리카공화국",
  },
  { name: "기타", code: "ETC", country: "ZA", countryName: "남아프리카공화국" },
  {
    name: "안타나나리보",
    code: "TNR",
    country: "MG",
    countryName: "마다가스카르",
  },
  { name: "노시베", code: "NOS", country: "MG", countryName: "마다가스카르" },
  { name: "툴레아르", code: "TLE", country: "MG", countryName: "마다가스카르" },
  { name: "기타", code: "ETC", country: "MG", countryName: "마다가스카르" },
  { name: "민스크", code: "MI", country: "BY", countryName: "벨라루스" },
  { name: "고멜", code: "HO", country: "BY", countryName: "벨라루스" },
  { name: "브레스트", code: "BR", country: "BY", countryName: "벨라루스" },
  { name: "비텝스크", code: "VI", country: "BY", countryName: "벨라루스" },
  { name: "그로드노", code: "GR", country: "BY", countryName: "벨라루스" },
  { name: "기타", code: "ETC", country: "BY", countryName: "벨라루스" },
  { name: "키이우", code: "KV", country: "UA", countryName: "우크라이나" },
  { name: "리비우", code: "LV", country: "UA", countryName: "우크라이나" },
  { name: "오데사", code: "OD", country: "UA", countryName: "우크라이나" },
  { name: "하르키우", code: "HA", country: "UA", countryName: "우크라이나" },
  { name: "드니프로", code: "DP", country: "UA", countryName: "우크라이나" },
  { name: "기타", code: "ETC", country: "UA", countryName: "우크라이나" },
  { name: "키시나우", code: "CU", country: "MD", countryName: "몰도바" },
  { name: "기타", code: "ETC", country: "MD", countryName: "몰도바" },
  { name: "트빌리시", code: "TB", country: "GE", countryName: "조지아" },
  { name: "바투미", code: "AJ", country: "GE", countryName: "조지아" },
  { name: "쿠타이시", code: "IM", country: "GE", countryName: "조지아" },
  { name: "기타", code: "ETC", country: "GE", countryName: "조지아" },
  { name: "바쿠", code: "BA", country: "AZ", countryName: "아제르바이잔" },
  { name: "간자", code: "GA", country: "AZ", countryName: "아제르바이잔" },
  { name: "기타", code: "ETC", country: "AZ", countryName: "아제르바이잔" },
  { name: "이스탄불", code: "34", country: "TR", countryName: "튀르키예" },
  { name: "앙카라", code: "06", country: "TR", countryName: "튀르키예" },
  { name: "이즈미르", code: "35", country: "TR", countryName: "튀르키예" },
  { name: "안탈리아", code: "07", country: "TR", countryName: "튀르키예" },
  {
    name: "카파도키아 (네브셰히르)",
    code: "50",
    country: "TR",
    countryName: "튀르키예",
  },
  { name: "트라브존", code: "61", country: "TR", countryName: "튀르키예" },
  { name: "콘야", code: "42", country: "TR", countryName: "튀르키예" },
  { name: "기타", code: "ETC", country: "TR", countryName: "튀르키예" },
  { name: "소피아", code: "SO", country: "BG", countryName: "불가리아" },
  { name: "플로브디프", code: "PV", country: "BG", countryName: "불가리아" },
  { name: "바르나", code: "VN", country: "BG", countryName: "불가리아" },
  { name: "부르가스", code: "BU", country: "BG", countryName: "불가리아" },
  { name: "루세", code: "RU", country: "BG", countryName: "불가리아" },
  { name: "기타", code: "ETC", country: "BG", countryName: "불가리아" },
  { name: "아테네", code: "AT", country: "GR", countryName: "그리스" },
  { name: "테살로니키", code: "TS", country: "GR", countryName: "그리스" },
  {
    name: "크레타 (이라클리온)",
    code: "CR",
    country: "GR",
    countryName: "그리스",
  },
  { name: "로드스", code: "RH", country: "GR", countryName: "그리스" },
  { name: "산토리니 (티라)", code: "ST", country: "GR", countryName: "그리스" },
  { name: "기타", code: "ETC", country: "GR", countryName: "그리스" },
  { name: "부쿠레슈티", code: "B", country: "RO", countryName: "루마니아" },
  { name: "클루지나포카", code: "CJ", country: "RO", countryName: "루마니아" },
  { name: "브라쇼브", code: "BV", country: "RO", countryName: "루마니아" },
  { name: "티미쇼아라", code: "TM", country: "RO", countryName: "루마니아" },
  { name: "콘스탄차", code: "CT", country: "RO", countryName: "루마니아" },
  { name: "기타", code: "ETC", country: "RO", countryName: "루마니아" },
  { name: "베오그라드", code: "BG", country: "RS", countryName: "세르비아" },
  { name: "노비사드", code: "NS", country: "RS", countryName: "세르비아" },
  { name: "니시", code: "NI", country: "RS", countryName: "세르비아" },
  { name: "기타", code: "ETC", country: "RS", countryName: "세르비아" },
  { name: "부다페스트", code: "BU", country: "HU", countryName: "헝가리" },
  { name: "데브레첸", code: "DE", country: "HU", countryName: "헝가리" },
  { name: "세게드", code: "SZ", country: "HU", countryName: "헝가리" },
  { name: "페치", code: "PE", country: "HU", countryName: "헝가리" },
  { name: "기타", code: "ETC", country: "HU", countryName: "헝가리" },
  {
    name: "브라티슬라바",
    code: "BL",
    country: "SK",
    countryName: "슬로바키아",
  },
  { name: "코시체", code: "KI", country: "SK", countryName: "슬로바키아" },
  { name: "질리나", code: "ZI", country: "SK", countryName: "슬로바키아" },
  { name: "프레쇼우", code: "PR", country: "SK", countryName: "슬로바키아" },
  { name: "기타", code: "ETC", country: "SK", countryName: "슬로바키아" },
  { name: "빈", code: "W", country: "AT", countryName: "오스트리아" },
  { name: "잘츠부르크", code: "S", country: "AT", countryName: "오스트리아" },
  {
    name: "인스브루크 (티롤)",
    code: "T",
    country: "AT",
    countryName: "오스트리아",
  },
  { name: "그라츠", code: "ST", country: "AT", countryName: "오스트리아" },
  { name: "린츠", code: "O", country: "AT", countryName: "오스트리아" },
  { name: "기타", code: "ETC", country: "AT", countryName: "오스트리아" },
  { name: "자그레브", code: "ZG", country: "HR", countryName: "크로아티아" },
  {
    name: "두브로브니크",
    code: "DU",
    country: "HR",
    countryName: "크로아티아",
  },
  { name: "스플리트", code: "ST", country: "HR", countryName: "크로아티아" },
  { name: "리예카", code: "RI", country: "HR", countryName: "크로아티아" },
  { name: "플리트비체", code: "PL", country: "HR", countryName: "크로아티아" },
  { name: "기타", code: "ETC", country: "HR", countryName: "크로아티아" },
  { name: "프라하", code: "PR", country: "CZ", countryName: "체코" },
  { name: "브르노", code: "BR", country: "CZ", countryName: "체코" },
  { name: "플젠", code: "PL", country: "CZ", countryName: "체코" },
  { name: "올로모우츠", code: "OL", country: "CZ", countryName: "체코" },
  { name: "체스키크루믈로프", code: "CK", country: "CZ", countryName: "체코" },
  { name: "기타", code: "ETC", country: "CZ", countryName: "체코" },
  { name: "바르샤바", code: "WA", country: "PL", countryName: "폴란드" },
  { name: "크라쿠프", code: "KR", country: "PL", countryName: "폴란드" },
  { name: "그단스크", code: "GD", country: "PL", countryName: "폴란드" },
  { name: "브로츠와프", code: "WR", country: "PL", countryName: "폴란드" },
  { name: "포즈난", code: "PO", country: "PL", countryName: "폴란드" },
  { name: "기타", code: "ETC", country: "PL", countryName: "폴란드" },
  { name: "로마", code: "RM", country: "IT", countryName: "이탈리아" },
  { name: "밀라노", code: "MI", country: "IT", countryName: "이탈리아" },
  { name: "피렌체", code: "FI", country: "IT", countryName: "이탈리아" },
  { name: "나폴리", code: "NA", country: "IT", countryName: "이탈리아" },
  { name: "베네치아", code: "VE", country: "IT", countryName: "이탈리아" },
  { name: "볼로냐", code: "BO", country: "IT", countryName: "이탈리아" },
  {
    name: "팔레르모 (시칠리아)",
    code: "PA",
    country: "IT",
    countryName: "이탈리아",
  },
  { name: "토리노", code: "TO", country: "IT", countryName: "이탈리아" },
  { name: "기타", code: "ETC", country: "IT", countryName: "이탈리아" },
  { name: "탈린", code: "EE-37", country: "EE", countryName: "에스토니아" },
  { name: "타르투", code: "EE-78", country: "EE", countryName: "에스토니아" },
  { name: "패르누", code: "EE-67", country: "EE", countryName: "에스토니아" },
  { name: "나르바", code: "EE-44", country: "EE", countryName: "에스토니아" },
  { name: "기타", code: "ETC", country: "EE", countryName: "에스토니아" },
  { name: "리가", code: "LV-RIX", country: "LV", countryName: "라트비아" },
  {
    name: "다우가프필스",
    code: "LV-DR",
    country: "LV",
    countryName: "라트비아",
  },
  { name: "리에파야", code: "LV-LP", country: "LV", countryName: "라트비아" },
  { name: "예카브필스", code: "LV-JK", country: "LV", countryName: "라트비아" },
  { name: "기타", code: "ETC", country: "LV", countryName: "라트비아" },
  { name: "빌뉴스", code: "LT-VL", country: "LT", countryName: "리투아니아" },
  { name: "카우나스", code: "LT-KU", country: "LT", countryName: "리투아니아" },
  {
    name: "클라이페다",
    code: "LT-KL",
    country: "LT",
    countryName: "리투아니아",
  },
  {
    name: "시아울랴이",
    code: "LT-SA",
    country: "LT",
    countryName: "리투아니아",
  },
  { name: "기타", code: "ETC", country: "LT", countryName: "리투아니아" },
  { name: "바르샤바", code: "PL-MZ", country: "PL", countryName: "폴란드" },
  { name: "크라쿠프", code: "PL-MA", country: "PL", countryName: "폴란드" },
  { name: "브로츠와프", code: "PL-DS", country: "PL", countryName: "폴란드" },
  { name: "그단스크", code: "PL-PM", country: "PL", countryName: "폴란드" },
  { name: "포즈난", code: "PL-WP", country: "PL", countryName: "폴란드" },
  { name: "기타", code: "ETC", country: "PL", countryName: "폴란드" },
  { name: "헬싱키", code: "FI-18", country: "FI", countryName: "핀란드" },
  { name: "탐페레", code: "FI-11", country: "FI", countryName: "핀란드" },
  { name: "투르쿠", code: "FI-19", country: "FI", countryName: "핀란드" },
  { name: "로바니에미", code: "FI-10", country: "FI", countryName: "핀란드" },
  { name: "기타", code: "ETC", country: "FI", countryName: "핀란드" },
  { name: "오슬로", code: "NO-03", country: "NO", countryName: "노르웨이" },
  { name: "베르겐", code: "NO-12", country: "NO", countryName: "노르웨이" },
  { name: "트롬쇠", code: "NO-54", country: "NO", countryName: "노르웨이" },
  { name: "스타방에르", code: "NO-11", country: "NO", countryName: "노르웨이" },
  { name: "기타", code: "ETC", country: "NO", countryName: "노르웨이" },
  { name: "코펜하겐", code: "DK-84", country: "DK", countryName: "덴마크" },
  { name: "오덴세", code: "DK-83", country: "DK", countryName: "덴마크" },
  { name: "오르후스", code: "DK-82", country: "DK", countryName: "덴마크" },
  { name: "올보르", code: "DK-81", country: "DK", countryName: "덴마크" },
  { name: "기타", code: "ETC", country: "DK", countryName: "덴마크" },
  { name: "베를린", code: "DE-BE", country: "DE", countryName: "독일" },
  { name: "함부르크", code: "DE-HH", country: "DE", countryName: "독일" },
  {
    name: "뮌헨 (바이에른)",
    code: "DE-BY",
    country: "DE",
    countryName: "독일",
  },
  {
    name: "프랑크푸르트 (헤센)",
    code: "DE-HE",
    country: "DE",
    countryName: "독일",
  },
  {
    name: "쾰른 (노르트라인-베스트팔렌)",
    code: "DE-NW",
    country: "DE",
    countryName: "독일",
  },
  { name: "기타", code: "ETC", country: "DE", countryName: "독일" },
  { name: "암스테르담", code: "NL-NH", country: "NL", countryName: "네덜란드" },
  { name: "로테르담", code: "NL-ZH", country: "NL", countryName: "네덜란드" },
  {
    name: "헤이그",
    code: "NL-ZH-HAGUE",
    country: "NL",
    countryName: "네덜란드",
  },
  { name: "위트레흐트", code: "NL-UT", country: "NL", countryName: "네덜란드" },
  { name: "기타", code: "ETC", country: "NL", countryName: "네덜란드" },
  { name: "브뤼셀", code: "BE-BRU", country: "BE", countryName: "벨기에" },
  { name: "안트베르펜", code: "BE-VAN", country: "BE", countryName: "벨기에" },
  { name: "헨트", code: "BE-VOV", country: "BE", countryName: "벨기에" },
  { name: "브뤼헤", code: "BE-VWV", country: "BE", countryName: "벨기에" },
  { name: "기타", code: "ETC", country: "BE", countryName: "벨기에" },
  { name: "파리", code: "FR-IDF", country: "FR", countryName: "프랑스" },
  { name: "리옹", code: "FR-ARA", country: "FR", countryName: "프랑스" },
  { name: "마르세유", code: "FR-PAC", country: "FR", countryName: "프랑스" },
  { name: "니스", code: "FR-PAC-NCE", country: "FR", countryName: "프랑스" },
  { name: "보르도", code: "FR-NAQ", country: "FR", countryName: "프랑스" },
  { name: "기타", code: "ETC", country: "FR", countryName: "프랑스" },
  { name: "마드리드", code: "ES-MD", country: "ES", countryName: "스페인" },
  {
    name: "바르셀로나 (카탈루냐)",
    code: "ES-CT",
    country: "ES",
    countryName: "스페인",
  },
  {
    name: "세비야 (안달루시아)",
    code: "ES-AN",
    country: "ES",
    countryName: "스페인",
  },
  { name: "그라나다", code: "ES-AN-GR", country: "ES", countryName: "스페인" },
  { name: "발렌시아", code: "ES-VC", country: "ES", countryName: "스페인" },
  { name: "기타", code: "ETC", country: "ES", countryName: "스페인" },
  { name: "리스본", code: "PT-11", country: "PT", countryName: "포르투갈" },
  { name: "포르투", code: "PT-13", country: "PT", countryName: "포르투갈" },
  { name: "코임브라", code: "PT-06", country: "PT", countryName: "포르투갈" },
  { name: "파티마", code: "PT-10", country: "PT", countryName: "포르투갈" },
  { name: "기타", code: "ETC", country: "PT", countryName: "포르투갈" },
  { name: "런던", code: "GB-LND", country: "GB", countryName: "영국" },
  { name: "맨체스터", code: "GB-MAN", country: "GB", countryName: "영국" },
  { name: "버밍엄", code: "GB-BIR", country: "GB", countryName: "영국" },
  { name: "에든버러", code: "GB-EDH", country: "GB", countryName: "영국" },
  { name: "글래스고", code: "GB-GLG", country: "GB", countryName: "영국" },
  { name: "리버풀", code: "GB-LIV", country: "GB", countryName: "영국" },
  { name: "브라이튼", code: "GB-BNH", country: "GB", countryName: "영국" },
  { name: "옥스퍼드", code: "GB-OXF", country: "GB", countryName: "영국" },
  { name: "케임브리지", code: "GB-CAM", country: "GB", countryName: "영국" },
  { name: "기타", code: "ETC", country: "GB", countryName: "영국" },
  { name: "더블린", code: "IE-D", country: "IE", countryName: "아일랜드" },
  { name: "골웨이", code: "IE-G", country: "IE", countryName: "아일랜드" },
  { name: "코크", code: "IE-C", country: "IE", countryName: "아일랜드" },
  { name: "리머릭", code: "IE-L", country: "IE", countryName: "아일랜드" },
  { name: "킬라니", code: "IE-KY", country: "IE", countryName: "아일랜드" },
  { name: "기타", code: "ETC", country: "IE", countryName: "아일랜드" },
  {
    name: "레이캬비크",
    code: "IS-1",
    country: "IS",
    countryName: "아이슬란드",
  },
  {
    name: "아쿠레이리",
    code: "IS-6",
    country: "IS",
    countryName: "아이슬란드",
  },
  {
    name: "이사피외르뒤르",
    code: "IS-4",
    country: "IS",
    countryName: "아이슬란드",
  },
  {
    name: "에일스타디르",
    code: "IS-7",
    country: "IS",
    countryName: "아이슬란드",
  },
  { name: "비크", code: "IS-8", country: "IS", countryName: "아이슬란드" },
  { name: "기타", code: "ETC", country: "IS", countryName: "아이슬란드" },
  { name: "누크", code: "GL-NU", country: "GL", countryName: "그린란드" },
  { name: "일루리사트", code: "GL-IL", country: "GL", countryName: "그린란드" },
  { name: "카나크", code: "GL-KQ", country: "GL", countryName: "그린란드" },
  { name: "카코르톡", code: "GL-KK", country: "GL", countryName: "그린란드" },
  { name: "기타", code: "ETC", country: "GL", countryName: "그린란드" },
  {
    name: "온타리오주 (토론토)",
    code: "CA-ON",
    country: "CA",
    countryName: "캐나다",
  },
  {
    name: "브리티시컬럼비아주 (밴쿠버)",
    code: "CA-BC",
    country: "CA",
    countryName: "캐나다",
  },
  {
    name: "퀘벡주 (몬트리올)",
    code: "CA-QC",
    country: "CA",
    countryName: "캐나다",
  },
  {
    name: "앨버타주 (캘거리, 에드먼턴)",
    code: "CA-AB",
    country: "CA",
    countryName: "캐나다",
  },
  {
    name: "매니토바주 (위니펙)",
    code: "CA-MB",
    country: "CA",
    countryName: "캐나다",
  },
  {
    name: "노바스코샤주 (핼리팩스)",
    code: "CA-NS",
    country: "CA",
    countryName: "캐나다",
  },
  { name: "기타", code: "ETC", country: "CA", countryName: "캐나다" },
  {
    name: "캘리포니아주 (로스앤젤레스, 샌프란시스코)",
    code: "US-CA",
    country: "US",
    countryName: "미국",
  },
  {
    name: "뉴욕주 (뉴욕시)",
    code: "US-NY",
    country: "US",
    countryName: "미국",
  },
  {
    name: "네바다주 (라스베이거스)",
    code: "US-NV",
    country: "US",
    countryName: "미국",
  },
  {
    name: "일리노이주 (시카고)",
    code: "US-IL",
    country: "US",
    countryName: "미국",
  },
  {
    name: "하와이주 (호놀룰루)",
    code: "US-HI",
    country: "US",
    countryName: "미국",
  },
  {
    name: "텍사스주 (오스틴, 휴스턴, 달라스)",
    code: "US-TX",
    country: "US",
    countryName: "미국",
  },
  { name: "워싱턴 D.C.", code: "US-DC", country: "US", countryName: "미국" },
  {
    name: "플로리다주 (마이애미, 올랜도)",
    code: "US-FL",
    country: "US",
    countryName: "미국",
  },
  {
    name: "매사추세츠주 (보스턴)",
    code: "US-MA",
    country: "US",
    countryName: "미국",
  },
  { name: "기타", code: "ETC", country: "US", countryName: "미국" },
  { name: "멕시코시티", code: "MX-CMX", country: "MX", countryName: "멕시코" },
  {
    name: "칸쿤 (킨타나로오)",
    code: "MX-ROO",
    country: "MX",
    countryName: "멕시코",
  },
  {
    name: "과달라하라 (할리스코)",
    code: "MX-JAL",
    country: "MX",
    countryName: "멕시코",
  },
  { name: "푸에블라", code: "MX-PUE", country: "MX", countryName: "멕시코" },
  {
    name: "몬테레이 (누에보레온)",
    code: "MX-NLE",
    country: "MX",
    countryName: "멕시코",
  },
  {
    name: "바하칼리포르니아수르 (로스카보스)",
    code: "MX-BCS",
    country: "MX",
    countryName: "멕시코",
  },
  { name: "기타", code: "ETC", country: "MX", countryName: "멕시코" },
  { name: "아바나", code: "CU-03", country: "CU", countryName: "쿠바" },
  {
    name: "산티아고 데 쿠바",
    code: "CU-13",
    country: "CU",
    countryName: "쿠바",
  },
  {
    name: "트리니다드 (산크티 스피리투스)",
    code: "CU-07",
    country: "CU",
    countryName: "쿠바",
  },
  { name: "기타", code: "ETC", country: "CU", countryName: "쿠바" },
  {
    name: "산토도밍고",
    code: "DO-01",
    country: "DO",
    countryName: "도미니카공화국",
  },
  {
    name: "푼타카나 (라 알타그라시아)",
    code: "DO-11",
    country: "DO",
    countryName: "도미니카공화국",
  },
  {
    name: "산티아고 데 로스 카바예로스",
    code: "DO-25",
    country: "DO",
    countryName: "도미니카공화국",
  },
  { name: "기타", code: "ETC", country: "DO", countryName: "도미니카공화국" },
  { name: "산후안", code: "PR-SJ", country: "PR", countryName: "푸에르토리코" },
  { name: "폰세", code: "PR-PO", country: "PR", countryName: "푸에르토리코" },
  {
    name: "마야게스",
    code: "PR-MA",
    country: "PR",
    countryName: "푸에르토리코",
  },
  { name: "기타", code: "ETC", country: "PR", countryName: "푸에르토리코" },
  {
    name: "과테말라시티",
    code: "GT-GU",
    country: "GT",
    countryName: "과테말라",
  },
  { name: "안티구아", code: "GT-SA", country: "GT", countryName: "과테말라" },
  { name: "기타", code: "ETC", country: "GT", countryName: "과테말라" },
  { name: "테구시갈파", code: "HN-FM", country: "HN", countryName: "온두라스" },
  {
    name: "로아탄 (이스라 데 라 바히아)",
    code: "HN-IB",
    country: "HN",
    countryName: "온두라스",
  },
  {
    name: "산페드로술라",
    code: "HN-CR",
    country: "HN",
    countryName: "온두라스",
  },
  { name: "기타", code: "ETC", country: "HN", countryName: "온두라스" },
  { name: "마나과", code: "NI-MN", country: "NI", countryName: "니카라과" },
  { name: "그라나다", code: "NI-GR", country: "NI", countryName: "니카라과" },
  {
    name: "산후안델수르 (리바스)",
    code: "NI-RI",
    country: "NI",
    countryName: "니카라과",
  },
  { name: "기타", code: "ETC", country: "NI", countryName: "니카라과" },
  { name: "산호세", code: "CR-SJ", country: "CR", countryName: "코스타리카" },
  {
    name: "리베리아 (과나카스테)",
    code: "CR-GU",
    country: "CR",
    countryName: "코스타리카",
  },
  {
    name: "푸에르토 비에호 (리몬)",
    code: "CR-LI",
    country: "CR",
    countryName: "코스타리카",
  },
  { name: "기타", code: "ETC", country: "CR", countryName: "코스타리카" },
  { name: "파나마시티", code: "PA-8", country: "PA", countryName: "파나마" },
  {
    name: "보케테 (치리키)",
    code: "PA-4",
    country: "PA",
    countryName: "파나마",
  },
  { name: "콜론", code: "PA-3", country: "PA", countryName: "파나마" },
  { name: "기타", code: "ETC", country: "PA", countryName: "파나마" },
  { name: "보고타", code: "CO-DC", country: "CO", countryName: "콜롬비아" },
  {
    name: "메데인 (안티오키아)",
    code: "CO-ANT",
    country: "CO",
    countryName: "콜롬비아",
  },
  {
    name: "카르타헤나 (볼리바르)",
    code: "CO-BOL",
    country: "CO",
    countryName: "콜롬비아",
  },
  {
    name: "칼리 (바예델카우카)",
    code: "CO-VAC",
    country: "CO",
    countryName: "콜롬비아",
  },
  {
    name: "산타마르타 (마그달레나)",
    code: "CO-MAG",
    country: "CO",
    countryName: "콜롬비아",
  },
  {
    name: "페레이라 (리스아랄다)",
    code: "CO-RIS",
    country: "CO",
    countryName: "콜롬비아",
  },
  {
    name: "산안드레스 제도",
    code: "CO-SAP",
    country: "CO",
    countryName: "콜롬비아",
  },
  { name: "기타", code: "ETC", country: "CO", countryName: "콜롬비아" },
  { name: "카라카스", code: "VE-D", country: "VE", countryName: "베네수엘라" },
  {
    name: "마라카이보 (수리아)",
    code: "VE-V",
    country: "VE",
    countryName: "베네수엘라",
  },
  {
    name: "발렌시아 (카라보보)",
    code: "VE-G",
    country: "VE",
    countryName: "베네수엘라",
  },
  {
    name: "바르키시메토 (라라)",
    code: "VE-K",
    country: "VE",
    countryName: "베네수엘라",
  },
  { name: "메리다", code: "VE-L", country: "VE", countryName: "베네수엘라" },
  {
    name: "푸에르토 라 크루스 (안소아테기)",
    code: "VE-B",
    country: "VE",
    countryName: "베네수엘라",
  },
  { name: "기타", code: "ETC", country: "VE", countryName: "베네수엘라" },
  { name: "조지타운", code: "GY-GT", country: "GY", countryName: "가이아나" },
  {
    name: "레지온 4 (데메라라-마하이카)",
    code: "GY-DEM",
    country: "GY",
    countryName: "가이아나",
  },
  {
    name: "레지온 9 (우파쿠마)",
    code: "GY-UPA",
    country: "GY",
    countryName: "가이아나",
  },
  { name: "기타", code: "ETC", country: "GY", countryName: "가이아나" },
  { name: "파라마리보", code: "SR-PM", country: "SR", countryName: "수리남" },
  {
    name: "니커리 (니커리 지구)",
    code: "SR-NI",
    country: "SR",
    countryName: "수리남",
  },
  { name: "브로코폰도", code: "SR-BR", country: "SR", countryName: "수리남" },
  { name: "기타", code: "ETC", country: "SR", countryName: "수리남" },
  {
    name: "카옌",
    code: "GF-CAY",
    country: "GF",
    countryName: "프랑스령 기아나",
  },
  {
    name: "생로랑뒤마로니",
    code: "GF-SLM",
    country: "GF",
    countryName: "프랑스령 기아나",
  },
  {
    name: "마투리",
    code: "GF-MAT",
    country: "GF",
    countryName: "프랑스령 기아나",
  },
  { name: "기타", code: "ETC", country: "GF", countryName: "프랑스령 기아나" },
  { name: "키토", code: "EC-P", country: "EC", countryName: "에콰도르" },
  {
    name: "과야킬 (과야스)",
    code: "EC-G",
    country: "EC",
    countryName: "에콰도르",
  },
  {
    name: "쿠엥카 (아수아이)",
    code: "EC-A",
    country: "EC",
    countryName: "에콰도르",
  },
  {
    name: "갈라파고스 제도",
    code: "EC-W",
    country: "EC",
    countryName: "에콰도르",
  },
  { name: "기타", code: "ETC", country: "EC", countryName: "에콰도르" },
  { name: "상파울루", code: "BR-SP", country: "BR", countryName: "브라질" },
  {
    name: "리우데자네이루",
    code: "BR-RJ",
    country: "BR",
    countryName: "브라질",
  },
  {
    name: "브라질리아 (연방구)",
    code: "BR-DF",
    country: "BR",
    countryName: "브라질",
  },
  {
    name: "바이아 (살바도르)",
    code: "BR-BA",
    country: "BR",
    countryName: "브라질",
  },
  {
    name: "파라나 (쿠리치바)",
    code: "BR-PR",
    country: "BR",
    countryName: "브라질",
  },
  {
    name: "아마조나스 (마나우스)",
    code: "BR-AM",
    country: "BR",
    countryName: "브라질",
  },
  {
    name: "페르남부쿠 (헤시피)",
    code: "BR-PE",
    country: "BR",
    countryName: "브라질",
  },
  { name: "기타", code: "ETC", country: "BR", countryName: "브라질" },
  { name: "리마", code: "PE-LMA", country: "PE", countryName: "페루" },
  { name: "쿠스코", code: "PE-CUS", country: "PE", countryName: "페루" },
  { name: "아레키파", code: "PE-ARE", country: "PE", countryName: "페루" },
  {
    name: "푸노 (티티카카호)",
    code: "PE-PUN",
    country: "PE",
    countryName: "페루",
  },
  {
    name: "이키토스 (로레토)",
    code: "PE-LOR",
    country: "PE",
    countryName: "페루",
  },
  { name: "기타", code: "ETC", country: "PE", countryName: "페루" },
  { name: "라파스", code: "BO-LP", country: "BO", countryName: "볼리비아" },
  { name: "수크레", code: "BO-H", country: "BO", countryName: "볼리비아" },
  { name: "산타크루스", code: "BO-S", country: "BO", countryName: "볼리비아" },
  { name: "코차밤바", code: "BO-C", country: "BO", countryName: "볼리비아" },
  { name: "오루로", code: "BO-O", country: "BO", countryName: "볼리비아" },
  { name: "기타", code: "ETC", country: "BO", countryName: "볼리비아" },
  {
    name: "산티아고 수도권",
    code: "CL-RM",
    country: "CL",
    countryName: "칠레",
  },
  { name: "발파라이소", code: "CL-VS", country: "CL", countryName: "칠레" },
  { name: "아타카마", code: "CL-AT", country: "CL", countryName: "칠레" },
  { name: "마우레 (탈카)", code: "CL-ML", country: "CL", countryName: "칠레" },
  {
    name: "라 아라우카니아 (뗌코)",
    code: "CL-AR",
    country: "CL",
    countryName: "칠레",
  },
  {
    name: "마가야네스 (파타고니아 남부)",
    code: "CL-MA",
    country: "CL",
    countryName: "칠레",
  },
  { name: "이스터섬", code: "CL-IP", country: "CL", countryName: "칠레" },
  { name: "기타", code: "ETC", country: "CL", countryName: "칠레" },
  { name: "아순시온", code: "PY-ASU", country: "PY", countryName: "파라과이" },
  {
    name: "알토 파라나 (시우다드 델 에스테)",
    code: "PY-10",
    country: "PY",
    countryName: "파라과이",
  },
  {
    name: "이타푸아 (엔카르나시온)",
    code: "PY-07",
    country: "PY",
    countryName: "파라과이",
  },
  { name: "기타", code: "ETC", country: "PY", countryName: "파라과이" },
  {
    name: "부에노스아이레스",
    code: "AR-C",
    country: "AR",
    countryName: "아르헨티나",
  },
  { name: "멘도사", code: "AR-M", country: "AR", countryName: "아르헨티나" },
  { name: "코르도바", code: "AR-X", country: "AR", countryName: "아르헨티나" },
  { name: "산타페", code: "AR-S", country: "AR", countryName: "아르헨티나" },
  {
    name: "바릴로체 (리오네그로)",
    code: "AR-R",
    country: "AR",
    countryName: "아르헨티나",
  },
  {
    name: "우수아이아 (티에라 델 푸에고)",
    code: "AR-V",
    country: "AR",
    countryName: "아르헨티나",
  },
  {
    name: "푸에르토 이과수 (미시오네스)",
    code: "AR-N",
    country: "AR",
    countryName: "아르헨티나",
  },
  { name: "기타", code: "ETC", country: "AR", countryName: "아르헨티나" },
  { name: "몬테비데오", code: "UY-MO", country: "UY", countryName: "우루과이" },
  {
    name: "말도나도 (푼타델에스테)",
    code: "UY-MA",
    country: "UY",
    countryName: "우루과이",
  },
  { name: "콜로니아", code: "UY-CO", country: "UY", countryName: "우루과이" },
  { name: "기타", code: "ETC", country: "UY", countryName: "우루과이" },
  {
    name: "로스 빙붕 지역 (미국/뉴질랜드 기지 중심)",
    code: "ROSS",
    country: "AQ",
    countryName: "남극",
  },
  {
    name: "남극 반도 (영국/아르헨티나/칠레 영유권 주장)",
    code: "PEN",
    country: "AQ",
    countryName: "남극",
  },
  {
    name: "아델리 랜드 (프랑스 관할 지역)",
    code: "ADE",
    country: "AQ",
    countryName: "남극",
  },
  {
    name: "퀸모드 랜드 (노르웨이 관할 지역)",
    code: "QML",
    country: "AQ",
    countryName: "남극",
  },
  {
    name: "빅토리아 랜드 (이탈리아/뉴질랜드 기지 위치)",
    code: "VIC",
    country: "AQ",
    countryName: "남극",
  },
  {
    name: "남극점 (아문센-스콧 기지 등)",
    code: "POLE",
    country: "AQ",
    countryName: "남극",
  },
  {
    name: "기타",
    code: "ETC",
    country: "AQ",
    countryName: "남극",
  },
  { name: "오클랜드", code: "NZ-AUK", country: "NZ", countryName: "뉴질랜드" },
  { name: "웰링턴", code: "NZ-WGN", country: "NZ", countryName: "뉴질랜드" },
  {
    name: "크라이스트처치 (캔터베리)",
    code: "NZ-CAN",
    country: "NZ",
    countryName: "뉴질랜드",
  },
  {
    name: "퀸스타운 (오타고)",
    code: "NZ-OTA",
    country: "NZ",
    countryName: "뉴질랜드",
  },
  {
    name: "로토루아 (베이 오브 플렌티)",
    code: "NZ-BOP",
    country: "NZ",
    countryName: "뉴질랜드",
  },
  {
    name: "해밀턴 (와이카토)",
    code: "NZ-WKO",
    country: "NZ",
    countryName: "뉴질랜드",
  },
  { name: "넬슨", code: "NZ-NSN", country: "NZ", countryName: "뉴질랜드" },
  {
    name: "더니든 (오타고)",
    code: "NZ-DUD",
    country: "NZ",
    countryName: "뉴질랜드",
  },
  { name: "기스번", code: "NZ-GIS", country: "NZ", countryName: "뉴질랜드" },
  { name: "타라나키", code: "NZ-TKI", country: "NZ", countryName: "뉴질랜드" },
  { name: "노스랜드", code: "NZ-NTL", country: "NZ", countryName: "뉴질랜드" },
  {
    name: "사우스랜드",
    code: "NZ-STL",
    country: "NZ",
    countryName: "뉴질랜드",
  },
  {
    name: "호크스베이",
    code: "NZ-HKB",
    country: "NZ",
    countryName: "뉴질랜드",
  },
  { name: "말버러", code: "NZ-MBH", country: "NZ", countryName: "뉴질랜드" },
  { name: "태즈먼", code: "NZ-TAS", country: "NZ", countryName: "뉴질랜드" },
  {
    name: "웨스트코스트",
    code: "NZ-WTC",
    country: "NZ",
    countryName: "뉴질랜드",
  },
  { name: "기타", code: "ETC", country: "NZ", countryName: "뉴질랜드" },
  {
    name: "비티레부섬 (수바, 난디)",
    code: "VITI",
    country: "FJ",
    countryName: "피지",
  },
  { name: "바누아레부섬", code: "VANUA", country: "FJ", countryName: "피지" },
  { name: "야사와 제도", code: "YASAWA", country: "FJ", countryName: "피지" },
  {
    name: "마마누카 제도",
    code: "MAMANUCA",
    country: "FJ",
    countryName: "피지",
  },
  { name: "기타", code: "ETC", country: "FJ", countryName: "피지" },
  {
    name: "우폴루섬 (수도 아피아)",
    code: "UPOLU",
    country: "WS",
    countryName: "사모아",
  },
  { name: "사바이이섬", code: "SAVAI", country: "WS", countryName: "사모아" },
  { name: "기타", code: "ETC", country: "WS", countryName: "사모아" },
  {
    name: "통가타푸섬 (수도 누쿠알로파)",
    code: "TONGATAPU",
    country: "TO",
    countryName: "통가",
  },
  { name: "바바우 제도", code: "VAVA", country: "TO", countryName: "통가" },
  { name: "하아파이 제도", code: "HAAPAI", country: "TO", countryName: "통가" },
  { name: "기타", code: "ETC", country: "TO", countryName: "통가" },
  {
    name: "타히티 (파페에테)",
    code: "TAHITI",
    country: "PF",
    countryName: "프랑스령 폴리네시아",
  },
  {
    name: "보라보라섬",
    code: "BORA",
    country: "PF",
    countryName: "프랑스령 폴리네시아",
  },
  {
    name: "모레아섬",
    code: "MOOREA",
    country: "PF",
    countryName: "프랑스령 폴리네시아",
  },
  {
    name: "기타",
    code: "ETC",
    country: "PF",
    countryName: "프랑스령 폴리네시아",
  },
  {
    name: "그랑드 테르 (누메아)",
    code: "GRANDETERRE",
    country: "NC",
    countryName: "뉴칼레도니아",
  },
  {
    name: "일 데 핑",
    code: "ILESDESPINS",
    country: "NC",
    countryName: "뉴칼레도니아",
  },
  { name: "기타", code: "ETC", country: "NC", countryName: "뉴칼레도니아" },
  { name: "괌 전체 (하갓냐)", code: "GU", country: "GU", countryName: "괌" },
  {
    name: "사이판",
    code: "SPN",
    country: "MP",
    countryName: "북마리아나 제도",
  },
  {
    name: "티니안",
    code: "TINIAN",
    country: "MP",
    countryName: "북마리아나 제도",
  },
  { name: "로타", code: "ROTA", country: "MP", countryName: "북마리아나 제도" },
  { name: "기타", code: "ETC", country: "MP", countryName: "북마리아나 제도" },
  { name: "말레 (수도)", code: "MLE", country: "MV", countryName: "몰디브" },
  { name: "북 말레 환초", code: "NMA", country: "MV", countryName: "몰디브" },
  { name: "남 말레 환초", code: "SMA", country: "MV", countryName: "몰디브" },
  {
    name: "아리아톨 (남/북)",
    code: "ARI",
    country: "MV",
    countryName: "몰디브",
  },
  { name: "바아 환초", code: "BAA", country: "MV", countryName: "몰디브" },
  { name: "라무 환초", code: "LAAMU", country: "MV", countryName: "몰디브" },
  { name: "기타", code: "ETC", country: "MV", countryName: "몰디브" },
  {
    name: "마에섬 (수도 빅토리아)",
    code: "MAHE",
    country: "SC",
    countryName: "세이셸",
  },
  { name: "프랄린섬", code: "PRASLIN", country: "SC", countryName: "세이셸" },
  { name: "라디그섬", code: "LA_DIQUE", country: "SC", countryName: "세이셸" },
  { name: "기타", code: "ETC", country: "SC", countryName: "세이셸" },
  {
    name: "마주로 환초 (수도)",
    code: "MAJ",
    country: "MH",
    countryName: "마셜 제도",
  },
  {
    name: "콰잘레인 환초",
    code: "KWA",
    country: "MH",
    countryName: "마셜 제도",
  },
  { name: "기타", code: "ETC", country: "MH", countryName: "마셜 제도" },
  {
    name: "라로통가섬 (수도 아바루아)",
    code: "RARO",
    country: "CK",
    countryName: "쿡 제도",
  },
  { name: "아이투타키섬", code: "AITU", country: "CK", countryName: "쿡 제도" },
  { name: "기타", code: "ETC", country: "CK", countryName: "쿡 제도" },
  {
    name: "타라와 (수도)",
    code: "TRW",
    country: "KI",
    countryName: "키리바시",
  },
  {
    name: "크리스마스섬 (키리티마티)",
    code: "KIRITI",
    country: "KI",
    countryName: "키리바시",
  },
  { name: "기타", code: "ETC", country: "KI", countryName: "키리바시" },
  {
    name: "푸나푸티 (수도)",
    code: "FUN",
    country: "TV",
    countryName: "투발루",
  },
  { name: "누이섬", code: "NUI", country: "TV", countryName: "투발루" },
  { name: "누쿠페타우섬", code: "NKT", country: "TV", countryName: "투발루" },
  { name: "기타", code: "ETC", country: "TV", countryName: "투발루" },
  { name: "서울특별시", code: "KR-11", country: "KR", countryName: "대한민국" },
  { name: "부산광역시", code: "KR-26", country: "KR", countryName: "대한민국" },
  { name: "대구광역시", code: "KR-27", country: "KR", countryName: "대한민국" },
  { name: "인천광역시", code: "KR-28", country: "KR", countryName: "대한민국" },
  { name: "광주광역시", code: "KR-29", country: "KR", countryName: "대한민국" },
  { name: "대전광역시", code: "KR-30", country: "KR", countryName: "대한민국" },
  { name: "울산광역시", code: "KR-31", country: "KR", countryName: "대한민국" },
  {
    name: "세종특별자치시",
    code: "KR-36",
    country: "KR",
    countryName: "대한민국",
  },
  { name: "수원시", code: "KR-31-001", country: "KR", countryName: "대한민국" },
  { name: "성남시", code: "KR-31-110", country: "KR", countryName: "대한민국" },
  {
    name: "의정부시",
    code: "KR-31-150",
    country: "KR",
    countryName: "대한민국",
  },
  { name: "안양시", code: "KR-31-200", country: "KR", countryName: "대한민국" },
  { name: "부천시", code: "KR-31-230", country: "KR", countryName: "대한민국" },
  { name: "광명시", code: "KR-31-250", country: "KR", countryName: "대한민국" },
  { name: "평택시", code: "KR-31-270", country: "KR", countryName: "대한민국" },
  {
    name: "동두천시",
    code: "KR-31-300",
    country: "KR",
    countryName: "대한민국",
  },
  { name: "안산시", code: "KR-31-310", country: "KR", countryName: "대한민국" },
  { name: "고양시", code: "KR-31-330", country: "KR", countryName: "대한민국" },
  { name: "과천시", code: "KR-31-340", country: "KR", countryName: "대한민국" },
  { name: "구리시", code: "KR-31-350", country: "KR", countryName: "대한민국" },
  {
    name: "남양주시",
    code: "KR-31-360",
    country: "KR",
    countryName: "대한민국",
  },
  { name: "오산시", code: "KR-31-370", country: "KR", countryName: "대한민국" },
  { name: "시흥시", code: "KR-31-380", country: "KR", countryName: "대한민국" },
  { name: "군포시", code: "KR-31-390", country: "KR", countryName: "대한민국" },
  { name: "의왕시", code: "KR-31-410", country: "KR", countryName: "대한민국" },
  { name: "하남시", code: "KR-31-420", country: "KR", countryName: "대한민국" },
  { name: "용인시", code: "KR-31-440", country: "KR", countryName: "대한민국" },
  { name: "파주시", code: "KR-31-470", country: "KR", countryName: "대한민국" },
  { name: "이천시", code: "KR-31-500", country: "KR", countryName: "대한민국" },
  { name: "안성시", code: "KR-31-520", country: "KR", countryName: "대한민국" },
  { name: "김포시", code: "KR-31-530", country: "KR", countryName: "대한민국" },
  { name: "화성시", code: "KR-31-570", country: "KR", countryName: "대한민국" },
  { name: "광주시", code: "KR-31-620", country: "KR", countryName: "대한민국" },
  { name: "양주시", code: "KR-31-650", country: "KR", countryName: "대한민국" },
  { name: "포천시", code: "KR-31-670", country: "KR", countryName: "대한민국" },
  { name: "여주시", code: "KR-31-690", country: "KR", countryName: "대한민국" },
  { name: "연천군", code: "KR-31-710", country: "KR", countryName: "대한민국" },
  { name: "춘천시", code: "KR-32-200", country: "KR", countryName: "대한민국" },
  { name: "원주시", code: "KR-32-270", country: "KR", countryName: "대한민국" },
  { name: "강릉시", code: "KR-32-250", country: "KR", countryName: "대한민국" },
  { name: "동해시", code: "KR-32-210", country: "KR", countryName: "대한민국" },
  { name: "태백시", code: "KR-32-230", country: "KR", countryName: "대한민국" },
  { name: "속초시", code: "KR-32-260", country: "KR", countryName: "대한민국" },
  { name: "삼척시", code: "KR-32-290", country: "KR", countryName: "대한민국" },
  { name: "청주시", code: "KR-33-210", country: "KR", countryName: "대한민국" },
  { name: "충주시", code: "KR-33-250", country: "KR", countryName: "대한민국" },
  { name: "제천시", code: "KR-33-270", country: "KR", countryName: "대한민국" },
  { name: "천안시", code: "KR-34-100", country: "KR", countryName: "대한민국" },
  { name: "공주시", code: "KR-34-140", country: "KR", countryName: "대한민국" },
  { name: "보령시", code: "KR-34-200", country: "KR", countryName: "대한민국" },
  { name: "아산시", code: "KR-34-290", country: "KR", countryName: "대한민국" },
  { name: "서산시", code: "KR-34-600", country: "KR", countryName: "대한민국" },
  { name: "전주시", code: "KR-35-110", country: "KR", countryName: "대한민국" },
  { name: "군산시", code: "KR-35-130", country: "KR", countryName: "대한민국" },
  { name: "익산시", code: "KR-35-150", country: "KR", countryName: "대한민국" },
  { name: "정읍시", code: "KR-35-200", country: "KR", countryName: "대한민국" },
  { name: "남원시", code: "KR-35-220", country: "KR", countryName: "대한민국" },
  { name: "김제시", code: "KR-35-240", country: "KR", countryName: "대한민국" },
  { name: "목포시", code: "KR-36-110", country: "KR", countryName: "대한민국" },
  { name: "여수시", code: "KR-36-180", country: "KR", countryName: "대한민국" },
  { name: "순천시", code: "KR-36-200", country: "KR", countryName: "대한민국" },
  { name: "나주시", code: "KR-36-230", country: "KR", countryName: "대한민국" },
  { name: "광양시", code: "KR-36-250", country: "KR", countryName: "대한민국" },
  { name: "포항시", code: "KR-37-110", country: "KR", countryName: "대한민국" },
  { name: "경주시", code: "KR-37-120", country: "KR", countryName: "대한민국" },
  { name: "김천시", code: "KR-37-140", country: "KR", countryName: "대한민국" },
  { name: "안동시", code: "KR-37-170", country: "KR", countryName: "대한민국" },
  { name: "구미시", code: "KR-37-250", country: "KR", countryName: "대한민국" },
  { name: "영주시", code: "KR-37-300", country: "KR", countryName: "대한민국" },
  { name: "영천시", code: "KR-37-310", country: "KR", countryName: "대한민국" },
  { name: "상주시", code: "KR-37-330", country: "KR", countryName: "대한민국" },
  { name: "경산시", code: "KR-37-350", country: "KR", countryName: "대한민국" },
  { name: "창원시", code: "KR-38-110", country: "KR", countryName: "대한민국" },
  { name: "통영시", code: "KR-38-130", country: "KR", countryName: "대한민국" },
  { name: "사천시", code: "KR-38-150", country: "KR", countryName: "대한민국" },
  { name: "진주시", code: "KR-38-270", country: "KR", countryName: "대한민국" },
  { name: "김해시", code: "KR-38-290", country: "KR", countryName: "대한민국" },
  { name: "밀양시", code: "KR-38-310", country: "KR", countryName: "대한민국" },
  { name: "거제시", code: "KR-38-330", country: "KR", countryName: "대한민국" },
  { name: "양산시", code: "KR-38-350", country: "KR", countryName: "대한민국" },
  { name: "제주시", code: "KR-39-110", country: "KR", countryName: "대한민국" },
  {
    name: "서귀포시",
    code: "KR-39-200",
    country: "KR",
    countryName: "대한민국",
  },
  {
    name: "서부주 (콜롬보)",
    code: "LK-11",
    country: "LK",
    countryName: "스리랑카",
  },
  {
    name: "중앙주 (캔디)",
    code: "LK-21",
    country: "LK",
    countryName: "스리랑카",
  },
  {
    name: "남부주 (갈레)",
    code: "LK-31",
    country: "LK",
    countryName: "스리랑카",
  },
  {
    name: "사바라가무와주",
    code: "LK-92",
    country: "LK",
    countryName: "스리랑카",
  },
  { name: "우바주", code: "LK-81", country: "LK", countryName: "스리랑카" },
  {
    name: "북서부주 (쿠루네갈라)",
    code: "LK-61",
    country: "LK",
    countryName: "스리랑카",
  },
  {
    name: "북중부주 (폴론나루와)",
    code: "LK-72",
    country: "LK",
    countryName: "스리랑카",
  },
  {
    name: "동부주 (트린코말리)",
    code: "LK-52",
    country: "LK",
    countryName: "스리랑카",
  },
  {
    name: "북부주 (자프나)",
    code: "LK-41",
    country: "LK",
    countryName: "스리랑카",
  },
  { name: "기타", code: "LK-ETC", country: "LK", countryName: "스리랑카" },
];
